// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: logs_assignment.proto

package logsAssignmentpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogAssignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string               `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	AssignmentId int64                `protobuf:"varint,2,opt,name=assignmentId,proto3" json:"assignmentId,omitempty"`
	Action       string               `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	CreatedAt    *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt    *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *LogAssignment) Reset() {
	*x = LogAssignment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logs_assignment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAssignment) ProtoMessage() {}

func (x *LogAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_logs_assignment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAssignment.ProtoReflect.Descriptor instead.
func (*LogAssignment) Descriptor() ([]byte, []int) {
	return file_logs_assignment_proto_rawDescGZIP(), []int{0}
}

func (x *LogAssignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogAssignment) GetAssignmentId() int64 {
	if x != nil {
		return x.AssignmentId
	}
	return 0
}

func (x *LogAssignment) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LogAssignment) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LogAssignment) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLogAssignmentByAssignmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignmentId int64 `protobuf:"varint,1,opt,name=assignmentId,proto3" json:"assignmentId,omitempty"`
}

func (x *GetLogAssignmentByAssignmentRequest) Reset() {
	*x = GetLogAssignmentByAssignmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logs_assignment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLogAssignmentByAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogAssignmentByAssignmentRequest) ProtoMessage() {}

func (x *GetLogAssignmentByAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_assignment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogAssignmentByAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetLogAssignmentByAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_logs_assignment_proto_rawDescGZIP(), []int{1}
}

func (x *GetLogAssignmentByAssignmentRequest) GetAssignmentId() int64 {
	if x != nil {
		return x.AssignmentId
	}
	return 0
}

type GetLogAssignmentByAssignmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*LogAssignment `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetLogAssignmentByAssignmentResponse) Reset() {
	*x = GetLogAssignmentByAssignmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logs_assignment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLogAssignmentByAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogAssignmentByAssignmentResponse) ProtoMessage() {}

func (x *GetLogAssignmentByAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_assignment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogAssignmentByAssignmentResponse.ProtoReflect.Descriptor instead.
func (*GetLogAssignmentByAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_logs_assignment_proto_rawDescGZIP(), []int{2}
}

func (x *GetLogAssignmentByAssignmentResponse) GetData() []*LogAssignment {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_logs_assignment_proto protoreflect.FileDescriptor

var file_logs_assignment_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcf, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x67,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x49, 0x0a, 0x23, 0x47, 0x65,
	0x74, 0x4c, 0x6f, 0x67, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x6f,
	0x67, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x83, 0x01, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x1c, 0x47, 0x65,
	0x74, 0x4c, 0x6f, 0x67, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x67, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x42, 0x79, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x6c, 0x6f, 0x67,
	0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logs_assignment_proto_rawDescOnce sync.Once
	file_logs_assignment_proto_rawDescData = file_logs_assignment_proto_rawDesc
)

func file_logs_assignment_proto_rawDescGZIP() []byte {
	file_logs_assignment_proto_rawDescOnce.Do(func() {
		file_logs_assignment_proto_rawDescData = protoimpl.X.CompressGZIP(file_logs_assignment_proto_rawDescData)
	})
	return file_logs_assignment_proto_rawDescData
}

var file_logs_assignment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_logs_assignment_proto_goTypes = []interface{}{
	(*LogAssignment)(nil),                        // 0: LogAssignment
	(*GetLogAssignmentByAssignmentRequest)(nil),  // 1: GetLogAssignmentByAssignmentRequest
	(*GetLogAssignmentByAssignmentResponse)(nil), // 2: GetLogAssignmentByAssignmentResponse
	(*timestamp.Timestamp)(nil),                  // 3: google.protobuf.Timestamp
}
var file_logs_assignment_proto_depIdxs = []int32{
	3, // 0: LogAssignment.createdAt:type_name -> google.protobuf.Timestamp
	3, // 1: LogAssignment.updatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: GetLogAssignmentByAssignmentResponse.data:type_name -> LogAssignment
	1, // 3: LogAssignmentService.GetLogAssignmentByAssignment:input_type -> GetLogAssignmentByAssignmentRequest
	2, // 4: LogAssignmentService.GetLogAssignmentByAssignment:output_type -> GetLogAssignmentByAssignmentResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_logs_assignment_proto_init() }
func file_logs_assignment_proto_init() {
	if File_logs_assignment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logs_assignment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogAssignment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logs_assignment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLogAssignmentByAssignmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logs_assignment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLogAssignmentByAssignmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logs_assignment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_assignment_proto_goTypes,
		DependencyIndexes: file_logs_assignment_proto_depIdxs,
		MessageInfos:      file_logs_assignment_proto_msgTypes,
	}.Build()
	File_logs_assignment_proto = out.File
	file_logs_assignment_proto_rawDesc = nil
	file_logs_assignment_proto_goTypes = nil
	file_logs_assignment_proto_depIdxs = nil
}
